# Site settings
title: Rajith's portfolio
email: radrajith@gmail.com
url: https://radrajith.github.io/
description: "My personal site to document and showcase my projects and also my credentials."
keywords: "Resume, Portfolio, Hire, job, Rajith, Raj, Radhakrishnan, Rajith Radhakrishnan, Engineer, Design Verification engineer, Hardware engineer, Software engineer, Coder, VLSI"
skills: "Electrical Engineer - Hardware and software enthusiast - Graduate Student"
meta_author: Radhakrishnan Rajith
#baseurl: /Jekyll_mysite
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: radrajith

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 285979 #007193 #18bc9c #80B3FF
  primary-rgb: "40,89,121" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Theme Credit

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rajith-radhakrishnan-265b5119/
  - title: github
    url: http://github.com/radrajith

# Postal address (add as many lines as necessary)
address:
  - line: New Hyde Park, NY 11040

# Credits content
credits: 'open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
